[project]
name = "blazar-tempest-plugin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tempest"
]

[project.entry-points."tempest.test_plugins"]
blazar_tests = "blazar_tempest_plugin.plugin:BlazarTempestPlugin"
